## Repaso general Numpy y Pandas

In [1]:
import numpy as np

In [2]:
enteros = [1,2,3,4,5]

In [3]:
np.array(enteros)

array([1, 2, 3, 4, 5])

In [5]:
np.array(enteros, dtype=np.int64)

array([1, 2, 3, 4, 5], dtype=int64)

In [6]:
np.array(enteros, dtype=np.int32)

array([1, 2, 3, 4, 5])

In [7]:
np.array(enteros, dtype=np.str_)

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [8]:
np.array(enteros, dtype=np.bool_)

array([ True,  True,  True,  True,  True])

In [9]:
1_000_000_000_000_000 # Para python es indiferente el uso de guión bajo

1000000000000000

In [10]:
arreglo = np.array(enteros, dtype=np.int32)

In [11]:
arreglo

array([1, 2, 3, 4, 5])

In [12]:
arreglo[0]

1

In [13]:
arreglo[-1]

5

In [16]:
arreglo = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=np.int32)

In [17]:
arreglo[:5]

array([1, 2, 3, 4, 5])

In [18]:
arreglo[::2]

array([1, 3, 5, 7, 9])

In [19]:
arreglo.size

10

In [20]:
arreglo.ndim

1

In [21]:
arreglo.shape

(10,)

In [23]:
arreglo.dtype

dtype('int32')

In [22]:
arreglo * 10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [24]:
arreglo + 1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
[1, 2] * 2

[1, 2, 1, 2]

In [26]:
[1, 2] * 10

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [28]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arreglo[[0, 1, 4, 6, 7, 8]]

array([1, 2, 5, 7, 8, 9])

In [30]:
arreglo = np.array([1, 2, 3, 4, 5], dtype=np.int32)

In [31]:
arreglo[[True, True, False, False, True]]

array([1, 2, 5])

In [32]:
arreglo[[1, 3, 4]]

array([2, 4, 5])

In [33]:
np.random.randint(1, 100, 10)

array([26,  6, 80,  4, 43, 53,  5, 95, 58, 95])

In [34]:
numeros = np.random.randint(1, 100, 10)

In [35]:
numeros * 10

array([100, 230, 990, 320, 290,  70, 610, 170, 950, 240])

In [36]:
numeros > 10

array([False,  True,  True,  True,  True, False,  True,  True,  True,
        True])

In [37]:
numeros = np.random.randint(1, 100, 50)

In [38]:
numeros

array([92, 29, 82, 10,  5, 98, 82, 13, 35, 98, 64, 63, 58, 53, 58, 25, 71,
       30, 11, 82, 25, 82, 85, 20, 88, 42, 99, 82,  8, 87, 58, 82, 40, 13,
       75, 38, 25, 71, 76, 96, 54, 66, 11, 86, 87, 88, 71, 66, 39, 72])

In [39]:
numeros[numeros > 50]

array([92, 82, 98, 82, 98, 64, 63, 58, 53, 58, 71, 82, 82, 85, 88, 99, 82,
       87, 58, 82, 75, 71, 76, 96, 54, 66, 86, 87, 88, 71, 66, 72])

In [40]:
numeros[numeros < 10]

array([5, 8])

In [41]:
# Obtener todos los elementos cuyo valor se encuentre en el rango 20-50
numeros[(numeros > 20) & (numeros < 50)]

array([29, 35, 25, 30, 25, 42, 40, 38, 25, 39])

In [42]:
numeros = np.random.randint(1, 100_000, 2000)

In [43]:
numeros[(numeros > 20_000) & (numeros < 50_000)]

array([28335, 41426, 39395, 21915, 33579, 43229, 22749, 24752, 38488,
       41146, 37707, 29223, 28430, 41934, 49479, 21379, 29343, 28092,
       26919, 40614, 39444, 48182, 47931, 47520, 31369, 25308, 21533,
       48876, 33865, 30648, 23607, 21323, 28166, 46054, 37095, 37373,
       21510, 48331, 41308, 30161, 30724, 40319, 21482, 43295, 31607,
       22024, 20447, 38548, 29691, 27443, 21101, 31123, 46491, 49423,
       29975, 33958, 46035, 31776, 33295, 39449, 25927, 24755, 47242,
       45715, 40956, 21197, 30736, 36162, 48125, 30123, 32370, 35494,
       31767, 38628, 29403, 38820, 48807, 20536, 46572, 41785, 30864,
       25494, 46695, 28341, 36328, 45737, 46125, 44938, 49909, 43421,
       27309, 47250, 20238, 36096, 46886, 23345, 34116, 31621, 35810,
       45117, 37247, 41644, 31825, 34554, 45714, 29421, 43671, 40041,
       49428, 48020, 36968, 28701, 28567, 47068, 47110, 44885, 25684,
       43948, 23071, 32473, 28826, 37132, 42254, 46517, 22693, 25219,
       35645, 35155,

In [44]:
import pandas as pd

In [45]:
numeros = np.random.randint(1, 100, 10)

In [46]:
numeros

array([64, 58, 32,  9, 98, 72, 16, 31, 20, 39])

In [48]:
serie = pd.Series(numeros)

In [49]:
serie

0    64
1    58
2    32
3     9
4    98
5    72
6    16
7    31
8    20
9    39
dtype: int32

In [50]:
serie[0]

64

In [51]:
serie[8]

20

In [52]:
numeros = np.random.randint(1, 100, 5)

In [54]:
serie = pd.Series(numeros, index=['a', 'b', 'c', 'd', 'e'])

In [55]:
serie

a     5
b    39
c    18
d    38
e    26
dtype: int32

In [56]:
serie['a']

5

In [57]:
serie.values

array([ 5, 39, 18, 38, 26])

In [58]:
serie = pd.Series(numeros, index=['a', 'b', 'c', 'd', 'e'], name='numbers')

In [59]:
serie.name

'numbers'

In [61]:
serie.size

5

In [62]:
serie.shape

(5,)

In [64]:
serie = pd.Series(
    data = np.random.randint(0, 10, 4),
    index = ['a', 'b', 'c', 'd'],
    name = 'numbers'
)

In [65]:
serie

a    5
b    7
c    6
d    4
Name: numbers, dtype: int32

In [70]:
usuarios = {
    'name': ['user1', 'user2', 'user3'],
    'email': ['user1@example.com','user2@example.com','user3@example.com']
}

In [71]:
usuarios

{'name': ['user1', 'user2', 'user3'],
 'email': ['user1@example.com', 'user2@example.com', 'user3@example.com']}

In [72]:
data = pd.DataFrame(usuarios)

In [73]:
data

name              email
0  user1  user1@example.com
1  user2  user2@example.com
2  user3  user3@example.com

In [74]:
data['name']

0    user1
1    user2
2    user3
Name: name, dtype: object

In [75]:
data['email']

0    user1@example.com
1    user2@example.com
2    user3@example.com
Name: email, dtype: object

In [77]:
data.name

0    user1
1    user2
2    user3
Name: name, dtype: object

In [76]:
data.email

0    user1@example.com
1    user2@example.com
2    user3@example.com
Name: email, dtype: object

## Ejercicios

In [68]:
import numpy as np
import pandas as pd

In [69]:
users = pd.read_csv('usersv2.csv')

In [78]:
users

name  age            username  \
0          Ms Fátima Martin   42      goldenmouse797   
1         Mrs Molly Garrett   30       smallpanda982   
2         Ms Veena Kulkarni   53       smalltiger174   
3          Miss Sheryl Cole   74     beautifulcat191   
4         Ms Nataša Subašić   55          bigbird256   
...                     ...  ...                 ...   
1995  Ms Viktoria Lauritsen   38       heavyzebra441   
1996   Mr Christian Sørhaug   28      goldensnake897   
1997       Ms Maria Peković   45         redzebra951   
1998      Mrs Nicole Jensen   78     beautifuldog292   
1999  Mr Percy Blankenstein   36  ticklishostrich632   

                               email         country postcode  gender  
0          fatima.martin@example.com           Spain    43746  female  
1          molly.garrett@example.com         Ireland    57660  female  
2         veena.kulkarni@example.com           India    29797  female  
3            sheryl.cole@example.com  United Kingdom  TH3 7XG  female  
4         natasa.subasic@example.com          Serbia    83260  female  
...                              ...             ...      ...     ...  
1995  viktoria.lauritsen@example.com          Norway     1545  female  
1996   christian.sorhaug@example.com          Norway     3614    male  
1997       maria.pekovic@example.com          Serbia    30159  female  
1998       nicole.jensen@example.com  United Kingdom  L9J 1QE  female  
1999  percy.blankenstein@example.com     Netherlands  3143 RR    male  

[2000 rows x 7 columns]

In [79]:
users.dropna()

name  age            username  \
0          Ms Fátima Martin   42      goldenmouse797   
1         Mrs Molly Garrett   30       smallpanda982   
2         Ms Veena Kulkarni   53       smalltiger174   
3          Miss Sheryl Cole   74     beautifulcat191   
4         Ms Nataša Subašić   55          bigbird256   
...                     ...  ...                 ...   
1995  Ms Viktoria Lauritsen   38       heavyzebra441   
1996   Mr Christian Sørhaug   28      goldensnake897   
1997       Ms Maria Peković   45         redzebra951   
1998      Mrs Nicole Jensen   78     beautifuldog292   
1999  Mr Percy Blankenstein   36  ticklishostrich632   

                               email         country postcode  gender  
0          fatima.martin@example.com           Spain    43746  female  
1          molly.garrett@example.com         Ireland    57660  female  
2         veena.kulkarni@example.com           India    29797  female  
3            sheryl.cole@example.com  United Kingdom  TH3 7XG  female  
4         natasa.subasic@example.com          Serbia    83260  female  
...                              ...             ...      ...     ...  
1995  viktoria.lauritsen@example.com          Norway     1545  female  
1996   christian.sorhaug@example.com          Norway     3614    male  
1997       maria.pekovic@example.com          Serbia    30159  female  
1998       nicole.jensen@example.com  United Kingdom  L9J 1QE  female  
1999  percy.blankenstein@example.com     Netherlands  3143 RR    male  

[2000 rows x 7 columns]

In [80]:
users.fillna({'age': 10})

name  age            username  \
0          Ms Fátima Martin   42      goldenmouse797   
1         Mrs Molly Garrett   30       smallpanda982   
2         Ms Veena Kulkarni   53       smalltiger174   
3          Miss Sheryl Cole   74     beautifulcat191   
4         Ms Nataša Subašić   55          bigbird256   
...                     ...  ...                 ...   
1995  Ms Viktoria Lauritsen   38       heavyzebra441   
1996   Mr Christian Sørhaug   28      goldensnake897   
1997       Ms Maria Peković   45         redzebra951   
1998      Mrs Nicole Jensen   78     beautifuldog292   
1999  Mr Percy Blankenstein   36  ticklishostrich632   

                               email         country postcode  gender  
0          fatima.martin@example.com           Spain    43746  female  
1          molly.garrett@example.com         Ireland    57660  female  
2         veena.kulkarni@example.com           India    29797  female  
3            sheryl.cole@example.com  United Kingdom  TH3 7XG  female  
4         natasa.subasic@example.com          Serbia    83260  female  
...                              ...             ...      ...     ...  
1995  viktoria.lauritsen@example.com          Norway     1545  female  
1996   christian.sorhaug@example.com          Norway     3614    male  
1997       maria.pekovic@example.com          Serbia    30159  female  
1998       nicole.jensen@example.com  United Kingdom  L9J 1QE  female  
1999  percy.blankenstein@example.com     Netherlands  3143 RR    male  

[2000 rows x 7 columns]

In [81]:
users.fillna({'age': users['age'].mean()})

name  age            username  \
0          Ms Fátima Martin   42      goldenmouse797   
1         Mrs Molly Garrett   30       smallpanda982   
2         Ms Veena Kulkarni   53       smalltiger174   
3          Miss Sheryl Cole   74     beautifulcat191   
4         Ms Nataša Subašić   55          bigbird256   
...                     ...  ...                 ...   
1995  Ms Viktoria Lauritsen   38       heavyzebra441   
1996   Mr Christian Sørhaug   28      goldensnake897   
1997       Ms Maria Peković   45         redzebra951   
1998      Mrs Nicole Jensen   78     beautifuldog292   
1999  Mr Percy Blankenstein   36  ticklishostrich632   

                               email         country postcode  gender  
0          fatima.martin@example.com           Spain    43746  female  
1          molly.garrett@example.com         Ireland    57660  female  
2         veena.kulkarni@example.com           India    29797  female  
3            sheryl.cole@example.com  United Kingdom  TH3 7XG  female  
4         natasa.subasic@example.com          Serbia    83260  female  
...                              ...             ...      ...     ...  
1995  viktoria.lauritsen@example.com          Norway     1545  female  
1996   christian.sorhaug@example.com          Norway     3614    male  
1997       maria.pekovic@example.com          Serbia    30159  female  
1998       nicole.jensen@example.com  United Kingdom  L9J 1QE  female  
1999  percy.blankenstein@example.com     Netherlands  3143 RR    male  

[2000 rows x 7 columns]

In [102]:
users['name'] # Serie

0            Ms Fátima Martin
1           Mrs Molly Garrett
2           Ms Veena Kulkarni
3            Miss Sheryl Cole
4           Ms Nataša Subašić
                ...          
1995    Ms Viktoria Lauritsen
1996     Mr Christian Sørhaug
1997         Ms Maria Peković
1998        Mrs Nicole Jensen
1999    Mr Percy Blankenstein
Name: name, Length: 2000, dtype: object

In [103]:
users[['name','email']] # DataFrame

name                           email
0          Ms Fátima Martin       fatima.martin@example.com
1         Mrs Molly Garrett       molly.garrett@example.com
2         Ms Veena Kulkarni      veena.kulkarni@example.com
3          Miss Sheryl Cole         sheryl.cole@example.com
4         Ms Nataša Subašić      natasa.subasic@example.com
...                     ...                             ...
1995  Ms Viktoria Lauritsen  viktoria.lauritsen@example.com
1996   Mr Christian Sørhaug   christian.sorhaug@example.com
1997       Ms Maria Peković       maria.pekovic@example.com
1998      Mrs Nicole Jensen       nicole.jensen@example.com
1999  Mr Percy Blankenstein  percy.blankenstein@example.com

[2000 rows x 2 columns]

### Taller

1. Obtener el nombre y correo de todos los usuarios

In [82]:
users[['name','email']] # SELECT campos

name                           email
0          Ms Fátima Martin       fatima.martin@example.com
1         Mrs Molly Garrett       molly.garrett@example.com
2         Ms Veena Kulkarni      veena.kulkarni@example.com
3          Miss Sheryl Cole         sheryl.cole@example.com
4         Ms Nataša Subašić      natasa.subasic@example.com
...                     ...                             ...
1995  Ms Viktoria Lauritsen  viktoria.lauritsen@example.com
1996   Mr Christian Sørhaug   christian.sorhaug@example.com
1997       Ms Maria Peković       maria.pekovic@example.com
1998      Mrs Nicole Jensen       nicole.jensen@example.com
1999  Mr Percy Blankenstein  percy.blankenstein@example.com

[2000 rows x 2 columns]

2. Obtener nombre de todos los usuarios cuyo sexo es femenino

In [83]:
users.columns

Index(['name', 'age', 'username', 'email', 'country', 'postcode', 'gender'], dtype='object')

In [84]:
users[users['gender'] == 'female'] #dataFrame

name  age         username  \
0          Ms Fátima Martin   42   goldenmouse797   
1         Mrs Molly Garrett   30    smallpanda982   
2         Ms Veena Kulkarni   53    smalltiger174   
3          Miss Sheryl Cole   74  beautifulcat191   
4         Ms Nataša Subašić   55       bigbird256   
...                     ...  ...              ...   
1992      Ms Floriana Ramos   24  happymeercat253   
1994           Ms Bella Lee   22  ticklishwolf569   
1995  Ms Viktoria Lauritsen   38    heavyzebra441   
1997       Ms Maria Peković   45      redzebra951   
1998      Mrs Nicole Jensen   78  beautifuldog292   

                               email         country postcode  gender  
0          fatima.martin@example.com           Spain    43746  female  
1          molly.garrett@example.com         Ireland    57660  female  
2         veena.kulkarni@example.com           India    29797  female  
3            sheryl.cole@example.com  United Kingdom  TH3 7XG  female  
4         natasa.subasic@example.com          Serbia    83260  female  
...                              ...             ...      ...     ...  
1992      floriana.ramos@example.com          Brazil    26630  female  
1994           bella.lee@example.com     New Zealand    15527  female  
1995  viktoria.lauritsen@example.com          Norway     1545  female  
1997       maria.pekovic@example.com          Serbia    30159  female  
1998       nicole.jensen@example.com  United Kingdom  L9J 1QE  female  

[1013 rows x 7 columns]

In [85]:
# si se quiere obtener un columna específica
users[users['gender'] == 'female']['name']

0            Ms Fátima Martin
1           Mrs Molly Garrett
2           Ms Veena Kulkarni
3            Miss Sheryl Cole
4           Ms Nataša Subašić
                ...          
1992        Ms Floriana Ramos
1994             Ms Bella Lee
1995    Ms Viktoria Lauritsen
1997         Ms Maria Peković
1998        Mrs Nicole Jensen
Name: name, Length: 1013, dtype: object

In [86]:
# si se quiere obtener dos o más columnas
users[users['gender'] == 'female'][['name','gender']]

name  gender
0          Ms Fátima Martin  female
1         Mrs Molly Garrett  female
2         Ms Veena Kulkarni  female
3          Miss Sheryl Cole  female
4         Ms Nataša Subašić  female
...                     ...     ...
1992      Ms Floriana Ramos  female
1994           Ms Bella Lee  female
1995  Ms Viktoria Lauritsen  female
1997       Ms Maria Peković  female
1998      Mrs Nicole Jensen  female

[1013 rows x 2 columns]

3. Obtener nombre de todos los usuarios cuyo sexo es masculino y tengan una edad mayor a 50

In [87]:
users[(users['gender'] == 'male') & (users['age'] > 50)]['name']

6                   Mr Oscar Olsen
10      Monsieur Francesco Leclerc
12                 Mr Sean Shelton
17                Mr Lennox Økland
19                   Mr Jose Wells
                   ...            
1980               Mr Sierd Donker
1983          Mr Alfred Williamson
1987                Mr Blake Slawa
1991                 Mr Jake Moore
1993            Mr Zachary Stevens
Name: name, Length: 461, dtype: object

In [88]:
users.name[(users.gender == 'male') & (users.age > 50)]

6                   Mr Oscar Olsen
10      Monsieur Francesco Leclerc
12                 Mr Sean Shelton
17                Mr Lennox Økland
19                   Mr Jose Wells
                   ...            
1980               Mr Sierd Donker
1983          Mr Alfred Williamson
1987                Mr Blake Slawa
1991                 Mr Jake Moore
1993            Mr Zachary Stevens
Name: name, Length: 461, dtype: object

data[filter(s)][column] / [[columns]]

4. Obtener todos los usuarios cuya edad sea mayor a 20

In [89]:
users[users['age'] > 20]

name  age            username  \
0          Ms Fátima Martin   42      goldenmouse797   
1         Mrs Molly Garrett   30       smallpanda982   
2         Ms Veena Kulkarni   53       smalltiger174   
3          Miss Sheryl Cole   74     beautifulcat191   
4         Ms Nataša Subašić   55          bigbird256   
...                     ...  ...                 ...   
1995  Ms Viktoria Lauritsen   38       heavyzebra441   
1996   Mr Christian Sørhaug   28      goldensnake897   
1997       Ms Maria Peković   45         redzebra951   
1998      Mrs Nicole Jensen   78     beautifuldog292   
1999  Mr Percy Blankenstein   36  ticklishostrich632   

                               email         country postcode  gender  
0          fatima.martin@example.com           Spain    43746  female  
1          molly.garrett@example.com         Ireland    57660  female  
2         veena.kulkarni@example.com           India    29797  female  
3            sheryl.cole@example.com  United Kingdom  TH3 7XG  female  
4         natasa.subasic@example.com          Serbia    83260  female  
...                              ...             ...      ...     ...  
1995  viktoria.lauritsen@example.com          Norway     1545  female  
1996   christian.sorhaug@example.com          Norway     3614    male  
1997       maria.pekovic@example.com          Serbia    30159  female  
1998       nicole.jensen@example.com  United Kingdom  L9J 1QE  female  
1999  percy.blankenstein@example.com     Netherlands  3143 RR    male  

[2000 rows x 7 columns]

In [90]:
users[users['age'] > 68]

name  age           username  \
3               Miss Sheryl Cole   74    beautifulcat191   
10    Monsieur Francesco Leclerc   72       smallfrog613   
13           Miss Violeta Santos   76   blackelephant682   
16                Mrs Navya Kini   77   ticklishsnake791   
17              Mr Lennox Økland   75  beautifulzebra118   
...                          ...  ...                ...   
1970       Monsieur Kevin Renaud   77  beautifulmouse669   
1981         Miss Maddison Ortiz   71     yellowsnake332   
1983        Mr Alfred Williamson   71      smallgoose340   
1993          Mr Zachary Stevens   70     organicfish890   
1998           Mrs Nicole Jensen   78    beautifuldog292   

                              email         country  postcode  gender  
3           sheryl.cole@example.com  United Kingdom   TH3 7XG  female  
10    francesco.leclerc@example.com     Switzerland      7478    male  
13       violeta.santos@example.com          Brazil     80046  female  
16           navya.kini@example.com           India     95665  female  
17        lennox.okland@example.com          Norway      5854    male  
...                             ...             ...       ...     ...  
1970       kevin.renaud@example.com     Switzerland      9644    male  
1981     maddison.ortiz@example.com  United Kingdom  MD6T 6PG  female  
1983  alfred.williamson@example.com       Australia       821    male  
1993    zachary.stevens@example.com       Australia      5384    male  
1998      nicole.jensen@example.com  United Kingdom   L9J 1QE  female  

[298 rows x 7 columns]

5. Obtener el nombre, país y edad del usuario más joven

In [91]:
users.sort_values('age')

name  age           username  \
1842        Mrs Yolanda Gordon   21      heavygoose878   
1160          Mr Veeti Laurila   21     blueostrich774   
740            Mr Brett Gibson   21      happygoose344   
306             Ms Julija Ilić   21  beautifultiger676   
1306            Mr Nelson Carr   21    purplerabbit563   
...                        ...  ...                ...   
927   Mr Jonathan Christiansen   78     organiclion815   
1998         Mrs Nicole Jensen   78    beautifuldog292   
1814         Mr Stanley Garcia   78      happymouse103   
79            Miss Sara Weyand   78   yellowmeercat474   
555            Ms Beate Eifler   78      purplebear112   

                                  email         country  postcode  gender  
1842         yolanda.gordon@example.com   United States     66237  female  
1160          veeti.laurila@example.com         Finland     50513    male  
740            brett.gibson@example.com  United Kingdom  GD9W 1UE    male  
306             julija.ilic@example.com          Serbia     22697  female  
1306            nelson.carr@example.com       Australia      2271    male  
...                                 ...             ...       ...     ...  
927   jonathan.christiansen@example.com         Denmark     75964    male  
1998          nicole.jensen@example.com  United Kingdom   L9J 1QE  female  
1814         stanley.garcia@example.com  United Kingdom  QZ05 8EB    male  
79              sara.weyand@example.com         Germany     32314  female  
555            beate.eifler@example.com         Germany     43490  female  

[2000 rows x 7 columns]

In [92]:
users.sort_values('age').head(1)

name  age       username                       email  \
1842  Mrs Yolanda Gordon   21  heavygoose878  yolanda.gordon@example.com   

            country postcode  gender  
1842  United States    66237  female

In [105]:
# El usuario más longevo
users.sort_values('age').tail(1)

name  age       username                     email  country  \
555  Ms Beate Eifler   78  purplebear112  beate.eifler@example.com  Germany   

    postcode  gender  
555    43490  female

In [104]:
users.sort_values(['age','name'], ascending=False).head(1)[['name', 'country', 'age']]

name country  age
1076  Ms تارا جعفری    Iran   78

In [94]:
users.sort_values('age').head(1)[['name', 'country', 'age']]

name        country  age
1842  Mrs Yolanda Gordon  United States   21

In [95]:
# si se ordena respecto a la edad y por nombre
users.sort_values(['age','name']).head(1)[['name', 'country', 'age']]

name      country  age
707  Miss Imogen Green  New Zealand   21

6. Obtener el username y correo electrónico de los usuarios cuya edad se encuentre en el rango 50 a 60

In [98]:
users[(users['age'] > 50) & (users['age'] < 60)]

name  age          username  \
2       Ms Veena Kulkarni   53     smalltiger174   
4       Ms Nataša Subašić   55        bigbird256   
11    Mrs Abigail Morales   56      lazyzebra356   
19          Mr Jose Wells   58      heavyswan589   
27      Mr Mylan Lefebvre   56     yellowswan337   
...                   ...  ...               ...   
1950      Miss Donna Rice   56       tinylion905   
1962       Mr Tom Mercier   53  beautifulfish989   
1969      Mr Eemeli Heino   55   whitemeercat543   
1972  Ms Emilie Jørgensen   53    goldentiger337   
1987       Mr Blake Slawa   51   whiteostrich177   

                             email         country  postcode  gender  
2       veena.kulkarni@example.com           India     29797  female  
4       natasa.subasic@example.com          Serbia     83260  female  
11     abigail.morales@example.com  United Kingdom  FS6Q 6ZU  female  
19          jose.wells@example.com       Australia      5039    male  
27      mylan.lefebvre@example.com          France     48082    male  
...                            ...             ...       ...     ...  
1950        donna.rice@example.com         Ireland     76380  female  
1962       tom.mercier@example.com          France     24953    male  
1969      eemeli.heino@example.com         Finland     28730    male  
1972  emilie.jorgensen@example.com         Denmark     73187  female  
1987       blake.slawa@example.com          Canada   B5E 8D8    male  

[321 rows x 7 columns]

In [100]:
users[(users['age'] > 50) & (users['age'] < 60)][['username','email','age']]

username                         email  age
2        smalltiger174    veena.kulkarni@example.com   53
4           bigbird256    natasa.subasic@example.com   55
11        lazyzebra356   abigail.morales@example.com   56
19        heavyswan589        jose.wells@example.com   58
27       yellowswan337    mylan.lefebvre@example.com   56
...                ...                           ...  ...
1950       tinylion905        donna.rice@example.com   56
1962  beautifulfish989       tom.mercier@example.com   53
1969   whitemeercat543      eemeli.heino@example.com   55
1972    goldentiger337  emilie.jorgensen@example.com   53
1987   whiteostrich177       blake.slawa@example.com   51

[321 rows x 3 columns]

7. Obtener el username de todos los usuarios cuyo correo **no** terminen con @example.com

In [106]:
users[users['email'].str.startswith('e')]['email']

35          ege.karabocek@example.com
44         elisa.iglesias@example.com
73             ethan.chan@example.com
78      emanuel.haukeland@example.com
93             ege.tokgoz@example.com
                    ...              
1917        erin.marshall@example.com
1921          edna.fields@example.com
1968          emil.larsen@example.com
1969         eemeli.heino@example.com
1972     emilie.jorgensen@example.com
Name: email, Length: 156, dtype: object

In [108]:
users[~users['email'].str.endswith('@example.com')]['email'] # ~ negación

Series([], Name: email, dtype: object)

8. Obtener el username de todos los usuarios cuyo país sea Alemania, Finlandia o Canadá

In [109]:
users[(users['country'] == 'Canada') | (users['country'] == 'Germany') | (users['country'] == 'Finland')]['username']

15           smalltiger986
18             whitecat263
29       brownbutterfly120
36      ticklishladybug412
40       organicleopard484
               ...        
1969       whitemeercat543
1973        orangezebra429
1986        goldenkoala606
1987       whiteostrich177
1989          brownwolf223
Name: username, Length: 316, dtype: object

In [110]:
users[users['country'].isin(['Canada','Finland','Germany'])]['username']

15           smalltiger986
18             whitecat263
29       brownbutterfly120
36      ticklishladybug412
40       organicleopard484
               ...        
1969       whitemeercat543
1973        orangezebra429
1986        goldenkoala606
1987       whiteostrich177
1989          brownwolf223
Name: username, Length: 316, dtype: object

9. Obtener el nombre y correo de todos los usuarios de sexo femenino cuyo país sea Alemania

In [111]:
users[(users['country'] == 'Germany') & (users['gender'] == 'female')][['name','email']]

name                               email
79              Miss Sara Weyand             sara.weyand@example.com
105          Miss Marina Heumann          marina.heumann@example.com
245            Miss Bozena Thimm            bozena.thimm@example.com
260          Miss Clara Springer          clara.springer@example.com
270          Miss Elvira Eichner          elvira.eichner@example.com
278              Mrs Sevim Stehr             sevim.stehr@example.com
330           Ms Ilona Heinemann         ilona.heinemann@example.com
340                Ms Nina Höfer              nina.hofer@example.com
346          Mrs Cäcilie Uhlmann         cacilie.uhlmann@example.com
447           Ms Liesbeth Völker         liesbeth.volker@example.com
450               Mrs Ella Leder              ella.leder@example.com
477           Miss Stella Schenk           stella.schenk@example.com
487              Ms Alexa Backes            alexa.backes@example.com
555              Ms Beate Eifler            beate.eifler@example.com
676                Ms Kira Bartz              kira.bartz@example.com
695            Miss Ingrid Demir            ingrid.demir@example.com
750         Mrs Elizabeth Lemmer        elizabeth.lemmer@example.com
757   Miss Anne-Kathrin Haußmann  anne-kathrin.haussmann@example.com
764              Miss Flora Reil              flora.reil@example.com
767              Ms Alida Köster            alida.koster@example.com
784          Miss Valeri Stenger          valeri.stenger@example.com
870        Miss Viviane Steinert        viviane.steinert@example.com
925          Mrs Harriet Schmidl         harriet.schmidl@example.com
1020          Ms Gabriela Dreher         gabriela.dreher@example.com
1132             Ms Estelle Poth            estelle.poth@example.com
1151           Ms Janette Arslan          janette.arslan@example.com
1152         Mrs Annemarie Zwick         annemarie.zwick@example.com
1278         Ms Emilie Stegemann        emilie.stegemann@example.com
1386        Miss Emilie Schubert         emilie.schubert@example.com
1518           Miss Gerda Handke            gerda.handke@example.com
1534             Ms Elwira Heyne            elwira.heyne@example.com
1626               Ms Ute Saller              ute.saller@example.com
1631              Ms Mia Schrage             mia.schrage@example.com
1639       Miss Christina Hammes        christina.hammes@example.com
1678          Miss Ronja Frühauf           ronja.fruhauf@example.com
1685       Mrs Evangelia Dreßler      evangelia.dressler@example.com
1716        Miss Brunhilde Liebl         brunhilde.liebl@example.com
1734     Miss Malgorzata Püschel      malgorzata.puschel@example.com
1745            Ms Traude Völker           traude.volker@example.com
1758       Miss Annette Hallmann        annette.hallmann@example.com
1790            Ms Ildiko Kröner           ildiko.kroner@example.com
1863          Miss Adolfine Holl           adolfine.holl@example.com
1864          Mrs Annabell Stang          annabell.stang@example.com
1868               Mrs Anne Ertl               anne.ertl@example.com
1896          Mrs Camilla Yilmaz          camilla.yilmaz@example.com
1904             Ms Anne Steffan            anne.steffan@example.com
1952           Mrs Dorota Stuber           dorota.stuber@example.com
1989          Miss Sylvana Stoll           sylvana.stoll@example.com

10. Obtener el promedio de edad de todos los usuarios de sexo femenino de Canadá mayores de 20 años

In [112]:
users[(users['country'] == 'Canada') & (users['gender'] == 'female') & (users['age'] > 20)].mean()

age    53.890909
dtype: float64

In [113]:
condition = (users['country'] == 'Canada') & (users['gender'] == 'female') & (users['age'] > 20)

In [114]:
users.age[condition].mean()

53.89090909090909

11. Conocer la cantidad de usuarios que residen en Finlandia

In [115]:
users[users['country'] == 'Finland']['name'].count()

103

12. Mostrar en consola la cantidad de hombres y mujeres en el dataframe

In [116]:
users.groupby('gender')['gender'].count()

gender
female    1013
male       987
Name: gender, dtype: int64

13. Mostrar en consola el país con más mujeres

In [117]:
users[users['gender'] == 'female'].groupby('country')['country'].count().sort_values(ascending=False)

country
France            61
Canada            55
Spain             53
Australia         52
Brazil            52
Denmark           51
New Zealand       50
United Kingdom    50
Mexico            50
Netherlands       49
India             49
Switzerland       49
Germany           48
Ireland           47
Finland           47
Turkey            45
United States     45
Norway            44
Serbia            42
Ukraine           41
Iran              33
Name: country, dtype: int64

In [118]:
users[users['gender'] == 'female'].groupby('country')['country'].count().sort_values(ascending=False).head(1)

country
France    61
Name: country, dtype: int64

14. Obtener los 3 países con más usuarios

In [119]:
users.groupby('country')['country'].count().sort_values(ascending=False).head(3)

country
Australia    112
Germany      108
Spain        106
Name: country, dtype: int64